name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install System Dependencies
      run: |
        sudo apt update
        sudo apt install -y zip unzip openjdk-17-jdk python3-pip libffi-dev libssl-dev autoconf automake libtool wget

    - name: Install Buildozer & Cython
      run: |
        pip install --upgrade pip
        pip install buildozer cython

    - name: Create EXACT SDK Structure for Buildozer
      run: |
        # Buildozer jo path expect kar raha hai wahi banate hain
        mkdir -p /home/runner/.buildozer/android/platform/android-sdk/tools/bin
        cd /home/runner/.buildozer/android/platform/android-sdk
        
        # Download tools in EXACT location
        wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools-linux-9477386_latest.zip
        mv cmdline-tools tools
        
        echo "ANDROID_HOME=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/home/runner/.buildozer/android/platform/android-sdk" >> $GITHUB_ENV

    - name: Accept SDK Licenses
      run: |
        cd /home/runner/.buildozer/android/platform/android-sdk/tools/bin
        yes | ./sdkmanager --sdk_root=../.. --licenses

    - name: Install Android Packages
      run: |
        cd /home/runner/.buildozer/android/platform/android-sdk/tools/bin
        ./sdkmanager --sdk_root=../.. "platform-tools" "platforms;android-33" "build-tools;33.0.2" "emulator"

    - name: Build APK
      run: |
        buildozer -v android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: my-app
        path: bin/*.apk
        retention-days: 30
