name: Build APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install Ubuntu deps
      run: |
        sudo apt update
        sudo apt install -y python3-dev python3-pip git zip unzip openjdk-17-jdk

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython buildozer

    - name: Download Android SDK
      run: |
        mkdir -p $HOME/android-sdk
        cd $HOME/android-sdk
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip -O sdk.zip
        unzip sdk.zip
        mkdir cmdline-tools
        mv cmdline-tools/* cmdline-tools/
        rm sdk.zip

    - name: Set ANDROID_HOME
      run: |
        echo "ANDROID_HOME=$HOME/android-sdk" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/android-sdk/cmdline-tools/bin:$HOME/android-sdk/platform-tools" >> $GITHUB_ENV
        echo "PATH=$PATH:$HOME/.local/bin" >> $GITHUB_ENV

    - name: Install SDK Tools
      run: |
        yes | $HOME/android-sdk/cmdline-tools/bin/sdkmanager --licenses
        $HOME/android-sdk/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: buildozer android debug
